import = []
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
padding = { x = 0, y = 0 }
dynamic_padding = true

opacity = 0.8
blur = true

dynamic_title = false
option_as_alt = "OnlyLeft"

[scrolling]
history = 10000

[font]

normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 16

[mouse]
hide_when_typing = true
