theme = "plain"
icons = "material"

# [[block]]
# block = "focused_window"
# show_marks = "all"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "battery"
interval = 10

# [[block]]
# block = "backlight"

[[block]]
block = "sound"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "time"
interval = 60
format = "%m-%d/%R"
