theme = "plain"
icons = "material"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "battery"
interval = 10

# [[block]]
# block = "backlight"

[[block]]
block = "sound"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "time"
interval = 60
format = "%m-%d/%R"
